refactor: enable statistics only in production builds and add the `STAT_ENABLE` env to control the `stat` function
wikimedia-gadgets/VariantAlly pull request #8
Opened 2023-12-08 05:32 UTC by sunafterrainwm

The statistics are completely meaningless for small sites or personal use, and don't seem to need to be present in debug builds. This pr turns off the statistical function of the debug build and provides the STAT_ENABLE env option to force function "stat" to be turned on or off.

2023-12-17 15:34 UTC, AnYiEE requested changes

2023-12-17 15:34 UTC, AnYiEE commented on gadgets/variant-ally/rollup.config.js
> +  : production;
`strToBool`可以改个名，比如`checkStatEnable`，然后：

```ts
const isProduction = process.env.NODE_ENV === 'production';
const isStatEnable = checkStatEnable(process.env.VA_STAT_ENABLE) || isProduction;
```

2023-12-17 15:34 UTC, AnYiEE commented on gadgets/variant-ally/rollup.config.js
> +
不需要JSDoc：

```ts
function checkStatEnable(env: string | undefined): boolen {
  return !['false', 'no'].includes(String(env).trim().toLowerCase());
}
```

2023-12-17 15:34 UTC, AnYiEE commented on gadgets/variant-ally/rollup.config.js
> +
我认为统计应默认启用，无论VA_STAT_ENABLE存在与否，当显式把值设置为false/no时才会禁用，所以不需要那么判断。当然如果有此特殊需求，可以忽略这里。

2023-12-18 11:12 UTC, diskdance commented
> The statistics are completely meaningless for small sites or personal use, and don't seem to need to be present in debug builds

本项目一开始就是专门为了中文维基百科的需求而定制的，所以其他站点并不在考虑范围内（见[此处](https://github.com/wikimedia-gadgets/VariantAlly/issues/2#issuecomment-1809379299)）。更何况从小工具的角度来说我认为本项目的结构已经较为复杂了，再增加一个flag个人认为没有必要。

2023-12-19 09:47 UTC, closed without merging